package webhook

import (
	"github.com/mailru/easyjson/jlexer"
	"github.com/mailru/easyjson/jwriter"
)

// This file was autogenerated using the easyjson library,
// it performs encoding/decoding of Notification JSONs
// with maximum performance

// MarshalEasyJSON encodes a Notification structure
// into a JSON using the Writer given as parameter.
func (v Notification) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson_encode(w, v)
}

// UnmarshalEasyJSON decodes a Notification structure
// from a JSON using the Lexer given as parameter.
func (v *Notification) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson_decode(l, v)
}

// easyjson_encode is a helper function for encoding
// a Notification structure. It receives as input parameter a
// Notification and returns as output parameter a Writer.
func easyjson_encode(out *jwriter.Writer, in Notification) {

	out.RawByte('{')

	out.String("service")
	out.RawByte(':')
	out.String(in.service)
	out.RawByte(',')

	out.String("recipient")
	out.RawString(":[")
	for index, value := range in.recipients {
		if index != 0 {
			out.RawByte(',')
		}
		out.String(value)
	}
	out.RawString("],")

	out.String("message")
	out.RawByte(':')
	out.String(in.message)

	out.RawByte('}')

}

// easyjson_decode is a helper function for decoding
// a Notification structure. It receives as input parameter a
// Lexer and returns as output parameter a Notification.
func easyjson_decode(in *jlexer.Lexer, out *Notification) {
	if in.IsNull() {
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
}
